### ISSUE TITLE
Memory leak in parser

### ISSUE THREAD

**Issue by Adamkadaban** [t94j0/adexplorersnapshot-rs#7]
I'm trying to parse a ~6GB ADExplorer snapshot file. 
This keeps causing my system to run out of memory.

According to heaptrack, the parser seems to be leaking memory.

![image](https://github.com/user-attachments/assets/969bc772-f84e-4946-8d5d-0d860dae4c18)

I'm unfamiliar with rust, but I assume it's because the memory you mmap is never freed?

**Comment by Adamkadaban** [comment]
nvm. it seems my system was just running out of memory and crashing before memory could be freed.

I will look for a solution to being more memory-efficient and PR if I find one.

**Comment by t94j0** [comment]
Gotcha. Thanks for looking into that. I definitely need to work on the memory management. I'm not great at Rust lifetimes, but that would be the right way to do it. We should only need to map the file once into memory instead of doing all these allocs: https://github.com/t94j0/adexplorersnapshot-rs/blob/master/src/parser/parser.rs#L34. `read_next_wstring` and `read_wstring_exact` shouldn't use `from_le_bytes` since it does an alloc.
I want to get back to this project soon, so I'll work on it when I do
